excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ABindoff.github.io
title: noise and other obscurations
tagline: making sense of it all (with statistics)
description: mired in obscurity
paginate: 7
