excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ABindoff.github.io
title: noise and other obscurations
tagline: making sense of it all (with statistics)
description: a place to collect my thoughts as much as share them
paginate: 7
